travis:
  secure:
    BINSTAR_TOKEN: weINC07jsnUC+DIOzxm3mHGfDBgpUNcSrUllP8uuqfpIM+HoFSBtqYiSTDfuLK7bEYanPtAkwTvUtlLZORB8eq2Y/A7wlHnpWla4x5vGBCi+r6cdLq5K7B2aRQSkdMg2F3OvO0KcaF4XFuo9+GE+DidPxu4XiZvOVwcz59i0oR3+5cZcj4p0D5eyfqcmzqBnYW8Xx/L07xnnD5e+QNXMKMSu2ShM3AK2yxQXXn3IUL4ryct2PX9qYYhj5NUUGY3N+YSP6XEE0u/zBTMYF5Y/MP9/YEUxJ/jOE5bgnaZKTasjYjVFRWPJWhR2H6Xx5FiiQnYijaS68K3bJfOqH8CusSvophK7L2rChHso/u/xtNS3r3Li6C6QMx3NEzMUrWqgeZW4FXTD2gDJpj26KIGe3Lqtqs1MT8Ij4R/AYgm51g+fHq+KLZHhhfaen500cEZhO58rjpbX5QNwP+50S9qdyvRP1pNOA6pdcoB82JeG1LCLNsoeoXGZf8TrjfPJDzEts2YoFpRF0Vxvx78YptFhX7pDjSuHG1hfVz7Y5WF3fN+9ZcoNLFeT5TkbHRJlMZmSZ0maQ7lA0AR3TtZzRH6XYsmNT7nXRjcF1Quu50Y7JRQUCG6+K0WQ+6g1E0+sl9Cp2gvAe1rAqBFLwhQ6HFgEw7uUF4K54QPLiHQUIIzQINs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
